# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s

  external_labels: {}

scrape_configs:
  - job_name: demo
    metrics_path: /metrics
    static_configs:
      - targets:
        - app:8000
