# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nginx:
  image:
    repository: nginx
    tag: stable

image:
  repository: meanpugdigital/django-prometheus-demo
  tag: latest
  pullPolicy: Always

postgresql:
  postgresqlUsername: postgres
  postgresqlDatabase: demo
  postgresqlPassword: letmein

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: demo.local
      paths:
        - /*
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
