# Generated by Django 2.2.5 on 2019-09-07 03:36

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xs', 'xsmall'), ('sm', 'small'), ('md', 'medium'), ('lg', 'large'), ('xl', 'xlarge')], default='md', max_length=31)),
                ('name', models.CharField(max_length=127)),
                ('age', models.IntegerField()),
            ]
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
            ]
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='walk distance (in meters)')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to='walker.Dog')),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to='walker.Walker')),
            ]
        ),
    ]
